#!/bin/sh
# Copyright 2023 - The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the',  help='License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an',  help='AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# A script to build a qemu release using the Google AOSP toolchain

# Check if the correct number of arguments is provided
if [ "$#" -ne 2 ]; then
    echo "Configure and build qemu for trusty"
    echo "Usage: $0 <destination> <distribution>"
    exit 1
fi

# Get the directory of the script
script_dir=$(dirname "$0")
aosp_dir=$script_dir/../../../..

# Convert relative path to absolute path
absolute_aosp=$(readlink -f "$aosp_dir" 2>/dev/null || realpath "$aosp_dir")

PATH="$absolute_aosp/prebuilts/build-tools/path/linux-x86:$PATH"
PATH="$absolute_aosp/prebuilts/python/linux-x86/bin:$PATH"


# Assign parameters to variables
destination="$1"
distribution="$2"

echo "-- Launching qemu configuration, build"
$absolute_aosp/prebuilts/bazel/linux-x86_64/bazel run @qemu//google/toolchain:amc -- setup --config $absolute_aosp/third_party/qemu/google/toolchain/qemu-trusty-build-config.jsonc --force --target linux --aosp $absolute_aosp  $destination/qemu-bld
$absolute_aosp/prebuilts/bazel/linux-x86_64/bazel run @qemu//google/toolchain:amc -- compile $destination/qemu-bld
$absolute_aosp/prebuilts/bazel/linux-x86_64/bazel run @qemu//google/toolchain:amc -- release $destination/qemu-bld $distribution
