/*
 * Copyright 2016-2023 NXP SPDX-License-Identifier: BSD-3-Clause
 *
 * Automatically generated by svd-gen-header.py from MIMXRT595S_cm33.xml
 */
#ifndef HW_ARM_SVD_OSTIMER_H
#define HW_ARM_SVD_OSTIMER_H

#include "hw/core/register.h"

/* OSTIMER */
#define OSTIMER_REGS_NO (8)

/* EVTIMER Low */
REG32(OSTIMER_EVTIMERL, 0x0);
/* EVTimer Count Value */
FIELD(OSTIMER_EVTIMERL, EVTIMER_COUNT_VALUE, 0, 32);

/* EVTIMER High */
REG32(OSTIMER_EVTIMERH, 0x4);
/* EVTimer Count Value */
FIELD(OSTIMER_EVTIMERH, EVTIMER_COUNT_VALUE, 0, 32);

/* Local Capture Low for CPU */
REG32(OSTIMER_CAPTURE_L, 0x8);
/* EVTimer Capture Value */
FIELD(OSTIMER_CAPTURE_L, CAPTURE_VALUE, 0, 32);

/* Local Capture High for CPU */
REG32(OSTIMER_CAPTURE_H, 0xC);
/* EVTimer Capture Value */
FIELD(OSTIMER_CAPTURE_H, CAPTURE_VALUE, 0, 32);

/* Local Match Low for CPU */
REG32(OSTIMER_MATCH_L, 0x10);
/* EVTimer Match Value */
FIELD(OSTIMER_MATCH_L, MATCH_VALUE, 0, 32);

/* Local Match High for CPU */
REG32(OSTIMER_MATCH_H, 0x14);
/* EVTimer Match Value */
FIELD(OSTIMER_MATCH_H, MATCH_VALUE, 0, 32);

/* OSTIMER Control for CPU */
REG32(OSTIMER_OSEVENT_CTRL, 0x1C);
/* Interrupt Flag */
FIELD(OSTIMER_OSEVENT_CTRL, OSTIMER_INTRFLAG, 0, 1);
/* Interrupt or Wake-Up Request */
FIELD(OSTIMER_OSEVENT_CTRL, OSTIMER_INTENA, 1, 1);
/* EVTimer Match Write Ready */
FIELD(OSTIMER_OSEVENT_CTRL, MATCH_WR_RDY, 2, 1);

#define OSTIMER_REGISTER_ACCESS_INFO_ARRAY(_name) \
    struct RegisterAccessInfo _name[OSTIMER_REGS_NO] = { \
        [0 ... OSTIMER_REGS_NO - 1] = { \
            .name = "", \
            .addr = -1, \
        }, \
        [0x0] = { \
            .name = "EVTIMERL", \
            .addr = 0x0, \
            .ro = 0xFFFFFFFF, \
            .reset = 0x0, \
        }, \
        [0x1] = { \
            .name = "EVTIMERH", \
            .addr = 0x4, \
            .ro = 0xFFFFFFFF, \
            .reset = 0x0, \
        }, \
        [0x2] = { \
            .name = "CAPTURE_L", \
            .addr = 0x8, \
            .ro = 0xFFFFFFFF, \
            .reset = 0x0, \
        }, \
        [0x3] = { \
            .name = "CAPTURE_H", \
            .addr = 0xC, \
            .ro = 0xFFFFFFFF, \
            .reset = 0x0, \
        }, \
        [0x4] = { \
            .name = "MATCH_L", \
            .addr = 0x10, \
            .ro = 0x0, \
            .reset = 0xFFFFFFFF, \
        }, \
        [0x5] = { \
            .name = "MATCH_H", \
            .addr = 0x14, \
            .ro = 0x0, \
            .reset = 0xFFFFFFFF, \
        }, \
        [0x7] = { \
            .name = "OSEVENT_CTRL", \
            .addr = 0x1C, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x0, \
        }, \
    }

#endif /* HW_ARM_SVD_OSTIMER_H */
