/*
 * MIPI HCI I3C Core state
 *
 * Copyright (C) 2025 Google, LLC
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef HCI_CORE_H
#define HCI_CORE_H

#include "hw/core/registerfields.h"
#include "system/memory.h"

#define HCI_CORE_MMIO_OFFSET 0x0
#define HCI_CORE_NUM_REGS 27

REG32(HCI_VERSION, 0x00)
REG32(HC_CONTROL, 0x04)
    FIELD(HC_CONTROL, IBA_INCLUDE,             0, 1)
    FIELD(HC_CONTROL, DATA_BYTE_ORDER_MODE,    4, 1)
    FIELD(HC_CONTROL, MODE_SELECTOR,           6, 1)
    FIELD(HC_CONTROL, I2C_DEV_PRESENT,         7, 1)
    FIELD(HC_CONTROL, HOT_JOIN_CTRL,           8, 1)
    FIELD(HC_CONTROL, HALT_ON_CMD_SEQ_TIMEOUT, 12, 1)
    FIELD(HC_CONTROL, ABORT,                   29, 1)
    FIELD(HC_CONTROL, RESUME,                  30, 1)
    FIELD(HC_CONTROL, ENABLE,                  31, 1)
REG32(CONTROLLER_DEVICE_ADDR, 0x08)
    FIELD(CONTROLLER_DEVICE_ADDR, DYNAMIC_ADDR,       16, 7)
    FIELD(CONTROLLER_DEVICE_ADDR, DYNAMIC_ADDR_VALID, 31, 1)
REG32(HC_CAPABILITIES, 0x0c)
    FIELD(HC_CAPABILITIES, COMBO_COMMAND,        2, 1)
    FIELD(HC_CAPABILITIES, AUTO_COMMAND,         3, 1)
    FIELD(HC_CAPABILITIES, STANDBY_CR_CAP,       5, 1)
    FIELD(HC_CAPABILITIES, HDR_DDR_EN,           6, 1)
    FIELD(HC_CAPABILITIES, HDR_TS_EN,            7, 1)
    FIELD(HC_CAPABILITIES, CMD_CCC_DEFBYTE,      10, 1)
    FIELD(HC_CAPABILITIES, CMD_SIZE,             20, 2)
    FIELD(HC_CAPABILITIES, SG_CAPABILITY_CR_EN,  28, 1)
    FIELD(HC_CAPABILITIES, SG_CAPABILITY_IBI_EN, 29, 1)
    FIELD(HC_CAPABILITIES, SG_CAPABILITY_DC_EN,  30, 1)
REG32(RESET_CONTROL, 0x10)
    FIELD(RESET_CONTROL, SOFT_RST,       0, 1)
    FIELD(RESET_CONTROL, CMD_QUEUE_RST,  1, 1)
    FIELD(RESET_CONTROL, RESP_QUEUE_RST, 2, 1)
    FIELD(RESET_CONTROL, TX_FIFO_RST,    3, 1)
    FIELD(RESET_CONTROL, RX_FIFO_RST,    4, 1)
    FIELD(RESET_CONTROL, IBI_QUEUE_RST,  5, 1)
REG32(PRESENT_STATE, 0x14)
    FIELD(PRESENT_STATE, CURRENT_CONTROLLER, 2, 1)
REG32(INTR_STATUS, 0x20)
    FIELD(INTR_STATUS, HC_INTERNAL_ERR_STAT,        10, 1)
    FIELD(INTR_STATUS, HC_SEQ_CANCEL_STAT,          11, 1)
    FIELD(INTR_STATUS, HC_WARN_CMD_SEQ_STALL_STAT,  12, 1)
    FIELD(INTR_STATUS, HC_ERR_CMD_SEQ_TIMEOUT_STAT, 13, 1)
REG32(INTR_STATUS_ENABLE, 0x24)
    FIELD(INTR_STATUS_ENABLE, HC_INTERNAL_ERR_STAT,        10, 1)
    FIELD(INTR_STATUS_ENABLE, HC_SEQ_CANCEL_STAT,          11, 1)
    FIELD(INTR_STATUS_ENABLE, HC_WARN_CMD_SEQ_STALL_STAT,  12, 1)
    FIELD(INTR_STATUS_ENABLE, HC_ERR_CMD_SEQ_TIMEOUT_STAT, 13, 1)
REG32(INTR_SIGNAL_ENABLE, 0x28)
    FIELD(INTR_SIGNAL_ENABLE, HC_INTERNAL_ERR_STAT,        10, 1)
    FIELD(INTR_SIGNAL_ENABLE, HC_SEQ_CANCEL_STAT,          11, 1)
    FIELD(INTR_SIGNAL_ENABLE, HC_WARN_CMD_SEQ_STALL_STAT,  12, 1)
    FIELD(INTR_SIGNAL_ENABLE, HC_ERR_CMD_SEQ_TIMEOUT_STAT, 13, 1)
REG32(INTR_FORCE, 0x2c)
    FIELD(INTR_FORCE, HC_INTERNAL_ERR_STAT,        10, 1)
    FIELD(INTR_FORCE, HC_SEQ_CANCEL_STAT,          11, 1)
    FIELD(INTR_FORCE, HC_WARN_CMD_SEQ_STALL_STAT,  12, 1)
    FIELD(INTR_FORCE, HC_ERR_CMD_SEQ_TIMEOUT_STAT, 13, 1)
REG32(DAT_SECTION_OFFSET, 0x30)
    FIELD(DAT_SECTION_OFFSET, DAT_TABLE_OFFSET, 0, 12)
    FIELD(DAT_SECTION_OFFSET, DAT_TABLE_SIZE,   12, 7)
    FIELD(DAT_SECTION_OFFSET, DAT_ENTRY_SIZE,   28, 4)
REG32(DCT_SECTION_OFFSET, 0x34)
    FIELD(DCT_SECTION_OFFSET, DCT_TABLE_OFFSET, 0, 12)
    FIELD(DCT_SECTION_OFFSET, DCT_TABLE_SIZE,   12, 7)
    FIELD(DCT_SECTION_OFFSET, DCT_TABLE_INDEX,  19, 5)
    FIELD(DCT_SECTION_OFFSET, DCT_ENTRY_SIZE,   28, 4)
REG32(RING_HEADERS_SECTION_OFFSET, 0x38)
    FIELD(RING_HEADERS_SECTION_OFFSET, RING_HEADER_SECTION_OFFSET, 0, 16)
REG32(PIO_SECTION_OFFSET, 0x3c)
    FIELD(PIO_SECTION_OFFSET, PIO_SECTION_OFFSET, 0, 16)
REG32(EXT_CAPS_SECTION_OFFSET, 0x40)
    FIELD(EXT_CAPS_SECTION_OFFSET, EXT_CAPS_SECTION_OFFSET, 0, 16)
REG32(INT_CTRL_CMDS_EN, 0x4c)
    FIELD(INT_CTRL_CMDS_EN, ICC_SUPPORT,         0, 1)
    FIELD(INT_CTRL_CMDS_EN, MIPI_CMDS_SUPPORTED, 1, 15)
REG32(IBI_NOTIFY_CTRL, 0x58)
    FIELD(IBI_NOTIFY_CTRL, NOTIFY_HJ_REJECTED,  0, 1)
    FIELD(IBI_NOTIFY_CTRL, NOTIFY_CRR_REJECTED, 1, 1)
    FIELD(IBI_NOTIFY_CTRL, NOTIFY_IBI_REJECTED, 3, 1)
REG32(DEV_CTX_BASE_LO, 0x60)
REG32(DEV_CTX_BASE_HI, 0x64)
REG32(DEV_CTX_SG, 0x68)

typedef struct HCICoreState {
    uint32_t regs[HCI_CORE_NUM_REGS];

    struct {
        uint32_t ring_header_section_offset;
    } cfg;

    MemoryRegion iomem;
} HCICoreState;

#endif /* HCI_CORE_H */
