/*
 * MIPI HCI I3C DMA state
 *
 * Copyright (C) 2025 Google, LLC
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef HCI_DMA_H
#define HCI_DMA_H

#include "hw/core/registerfields.h"
#include "system/memory.h"

/* Header */
REG32(RHS_CONTROL, 0x00)
    FIELD(RHS_CONTROL, MAX_HEADER_COUNT,            0, 4)
    FIELD(RHS_CONTROL, MAX_HEADER_COUNT_CAPABILITY, 4, 4)
    FIELD(RHS_CONTROL, HEADER_SIZE,                 16, 8)
    FIELD(RHS_CONTROL, PREAMBLE_SIZE,               24, 8)
REG32(RH0_OFFSET, 0x04)
/* Ring status. */
REG32(CR_SETUP, 0x00)
    FIELD(CR_SETUP, RING_SIZE,        0, 8)
    FIELD(CR_SETUP, RESP_STRUCT_SIZE, 16, 8)
    FIELD(CR_SETUP, XFER_STRUCT_SIZE, 24, 8)
REG32(IBI_SETUP, 0x04)
    FIELD(IBI_SETUP, CHUNK_COUNT,            0, 10)
    FIELD(IBI_SETUP, CHUNK_SIZE,             10, 3)
    FIELD(IBI_SETUP, IBI_STATUS_RING_SIZE,   16, 8)
    FIELD(IBI_SETUP, IBI_STATUS_STRUCT_SIZE, 24, 8)
REG32(CHUNK_CONTROL, 0x08)
REG32(RH_INTR_STATUS, 0x10)
    FIELD(RH_INTR_STATUS, TRANSFER_ABORT_STAT,      5, 1)
    FIELD(RH_INTR_STATUS, IBI_RING_FULL_STAT,       6, 1)
    FIELD(RH_INTR_STATUS, TRANSFER_ERR_STAT,        9, 1)
    FIELD(RH_INTR_STATUS, RING_OP_STAT,             10, 1)
    FIELD(RH_INTR_STATUS, TRANSFER_COMPLETION_STAT, 11, 1)
    FIELD(RH_INTR_STATUS, IBI_READY_STAT,           12, 1)
REG32(RH_INTR_STATUS_ENABLE, 0x14)
    FIELD(RH_INTR_STATUS_ENABLE, TRANSFER_ABORT_STAT,      5, 1)
    FIELD(RH_INTR_STATUS_ENABLE, IBI_RING_FULL_STAT,       6, 1)
    FIELD(RH_INTR_STATUS_ENABLE, TRANSFER_ERR_STAT,        9, 1)
    FIELD(RH_INTR_STATUS_ENABLE, RING_OP_STAT,             10, 1)
    FIELD(RH_INTR_STATUS_ENABLE, TRANSFER_COMPLETION_STAT, 11, 1)
    FIELD(RH_INTR_STATUS_ENABLE, IBI_READY_STAT,           12, 1)
REG32(RH_INTR_SIGNAL_ENABLE, 0x18)
    FIELD(RH_INTR_SIGNAL_ENABLE, TRANSFER_ABORT_STAT,      5, 1)
    FIELD(RH_INTR_SIGNAL_ENABLE, IBI_RING_FULL_STAT,       6, 1)
    FIELD(RH_INTR_SIGNAL_ENABLE, TRANSFER_ERR_STAT,        9, 1)
    FIELD(RH_INTR_SIGNAL_ENABLE, RING_OP_STAT,             10, 1)
    FIELD(RH_INTR_SIGNAL_ENABLE, TRANSFER_COMPLETION_STAT, 11, 1)
    FIELD(RH_INTR_SIGNAL_ENABLE, IBI_READY_STAT,           12, 1)
REG32(RH_INTR_FORCE, 0x1c)
    FIELD(RH_INTR_FORCE, TRANSFER_ABORT_STAT,      5, 1)
    FIELD(RH_INTR_FORCE, IBI_RING_FULL_STAT,       6, 1)
    FIELD(RH_INTR_FORCE, TRANSFER_ERR_STAT,        9, 1)
    FIELD(RH_INTR_FORCE, RING_OP_STAT,             10, 1)
    FIELD(RH_INTR_FORCE, TRANSFER_COMPLETION_STAT, 11, 1)
    FIELD(RH_INTR_FORCE, IBI_READY_STAT,           12, 1)
REG32(RH_STATUS, 0x20)
    FIELD(RH_STATUS, RING_ENABLED, 0, 1)
    FIELD(RH_STATUS, RING_RUNNING, 1, 1)
    FIELD(RH_STATUS, RING_ABORTED, 2, 1)
    FIELD(RH_STATUS, RING_LOCKED,  3, 1)
REG32(RH_CONTROL, 0x24)
    FIELD(RH_CONTROL, RING_ENABLED, 0, 1)
    FIELD(RH_CONTROL, RING_RS,      1, 1)
    FIELD(RH_CONTROL, RING_ABORT,   2, 1)
REG32(RH_OPERATION1, 0x28)
    FIELD(RH_OPERATION1, CR_ENQ_PTR,    0, 8)
    FIELD(RH_OPERATION1, CR_SW_DEQ_PTR, 8, 8)
    FIELD(RH_OPERATION1, IBI_DEQ_PTR,   16, 8)
REG32(RH_OPERATION2, 0x2c)
    FIELD(RH_OPERATION2, CR_DEQ_PTR,  0, 8)
    FIELD(RH_OPERATION2, IBI_ENQ_PTR, 16, 8)
REG32(RH_CMD_RING_BASE_LO, 0x30)
REG32(RH_CMD_RING_BASE_HI, 0x34)
REG32(RH_RESP_RING_BASE_LO, 0x38)
REG32(RH_RESP_RING_BASE_HI, 0x3c)
REG32(RH_IBI_STATUS_RING_BASE_LO, 0x40)
REG32(RH_IBI_STATUS_RING_BASE_HI, 0x44)
REG32(RH_IBI_DATA_RING_BASE_LO, 0x48)
REG32(RH_IBI_DATA_RING_BASE_HI, 0x4c)

#endif
