/*
 * MIPI HCI I3C PIO state
 *
 * Copyright (C) 2025 Google, LLC
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef HCI_PIO_H
#define HCI_PIO_H

#include "hw/core/registerfields.h"
#include "system/memory.h"

#define HCI_PIO_NUM_REGS 12

REG32(COMMAND_QUEUE_PORT, 0x00)
REG32(RESPONSE_QUEUE_PORT, 0x04)
REG32(XFER_DATA_PORT, 0x08)
REG32(IBI_PORT, 0x0c)
REG32(QUEUE_THLD_CTRL, 0x10)
    FIELD(QUEUE_THLD_CTRL, CMD_EMPTY_BUF_THLD,    0, 8)
    FIELD(QUEUE_THLD_CTRL, RESP_BUF_THLD,         8, 8)
    FIELD(QUEUE_THLD_CTRL, IBI_DATA_SEGMENT_SIZE, 16, 8)
    FIELD(QUEUE_THLD_CTRL, IBI_STATUS_THLD,       24, 8)
REG32(DATA_BUFFER_THLD_CTRL, 0x14)
    FIELD(DATA_BUFFER_THLD_CTRL, TX_BUF_THLD,   0, 3)
    FIELD(DATA_BUFFER_THLD_CTRL, RX_BUF_THLD,   8, 3)
    FIELD(DATA_BUFFER_THLD_CTRL, TX_START_THLD, 16, 3)
    FIELD(DATA_BUFFER_THLD_CTRL, RX_START_THLD, 24, 3)
REG32(QUEUE_SIZE, 0x18)
    FIELD(QUEUE_SIZE, CR_QUEUE_SIZE,       0, 8)
    FIELD(QUEUE_SIZE, IBI_STATUS_SIZE,     8, 8)
    FIELD(QUEUE_SIZE, RX_DATA_BUFFER_SIZE, 16, 8)
    FIELD(QUEUE_SIZE, TX_DATA_BUFFER_SIZE, 24, 8)
REG32(PIO_INTR_STATUS, 0x20)
    FIELD(PIO_INTR_STATUS, TX_THLD_STAT,         0, 1)
    FIELD(PIO_INTR_STATUS, RX_THLD_STAT,         1, 1)
    FIELD(PIO_INTR_STATUS, IBI_STATUS_THLD_STAT, 2, 1)
    FIELD(PIO_INTR_STATUS, CMD_QUEUE_READY_STAT, 3, 1)
    FIELD(PIO_INTR_STATUS, RESP_READY_STAT,      4, 1)
    FIELD(PIO_INTR_STATUS, TRANSFER_ABORT_STAT,  5, 1)
    FIELD(PIO_INTR_STATUS, TRANSFER_ERR_STAT,    9, 1)
REG32(PIO_INTR_STATUS_ENABLE, 0x24)
    FIELD(PIO_INTR_STATUS_ENABLE, TX_THLD_STAT_EN,         0, 1)
    FIELD(PIO_INTR_STATUS_ENABLE, RX_THLD_STAT_EN,         1, 1)
    FIELD(PIO_INTR_STATUS_ENABLE, IBI_STATUS_THLD_STAT_EN, 2, 1)
    FIELD(PIO_INTR_STATUS_ENABLE, CMD_QUEUE_READY_STAT_EN, 3, 1)
    FIELD(PIO_INTR_STATUS_ENABLE, RESP_READY_STAT_EN,      4, 1)
    FIELD(PIO_INTR_STATUS_ENABLE, TRANSFER_ABORT_STAT_EN,  5, 1)
    FIELD(PIO_INTR_STATUS_ENABLE, TRANSFER_ERR_STAT_EN,    9, 1)
REG32(PIO_INTR_SIGNAL_ENABLE, 0x28)
    FIELD(PIO_INTR_SIGNAL_ENABLE, TX_THLD_SIGNAL_EN,         0, 1)
    FIELD(PIO_INTR_SIGNAL_ENABLE, RX_THLD_SIGNAL_EN,         1, 1)
    FIELD(PIO_INTR_SIGNAL_ENABLE, IBI_STATUS_THLD_SIGNAL_EN, 2, 1)
    FIELD(PIO_INTR_SIGNAL_ENABLE, CMD_QUEUE_READY_SIGNAL_EN, 3, 1)
    FIELD(PIO_INTR_SIGNAL_ENABLE, RESP_READY_SIGNAL_EN,      4, 1)
    FIELD(PIO_INTR_SIGNAL_ENABLE, TRANSFER_ABORT_SIGNAL_EN,  5, 1)
    FIELD(PIO_INTR_SIGNAL_ENABLE, TRANSFER_ERR_SIGNAL_EN,    9, 1)
REG32(PIO_INTR_FORCE, 0x2c)
    FIELD(PIO_INTR_FORCE, TX_THLD_FORCE,         0, 1)
    FIELD(PIO_INTR_FORCE, RX_THLD_FORCE,         1, 1)
    FIELD(PIO_INTR_FORCE, IBI_STATUS_THLD_FORCE, 2, 1)
    FIELD(PIO_INTR_FORCE, CMD_QUEUE_READY_FORCE, 3, 1)
    FIELD(PIO_INTR_FORCE, RESP_READY_FORCE,      4, 1)
    FIELD(PIO_INTR_FORCE, TRANSFER_ABORT_FORCE,  5, 1)
    FIELD(PIO_INTR_FORCE, TRANSFER_ERR_FORCE,    9, 1)

typedef struct HCIPIOState {
    MemoryRegion mmio;
} HCIPIOState;

#endif
